# Generated by Django 5.0.6 on 2024-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='data',
            field=models.TextField(max_length=500),
        ),
    ]
